notifications:
  email: false

language: python            # this works for Linux but is an error on macOS or Windows
jobs:
  include:
    - name: "Python 3.8.0 on Xenial Linux"
      python: 3.8           # this works for Linux but is ignored on macOS or Windows
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
      before_install:
        - python3 --version
    - name: "Python 3.8.0 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH

# install dependencies
install:
  - pip3 install --upgrade pip  # all three OSes agree about 'pip3'
  - sudo pip3 install -r requirements.txt || pip3 install -r requirements.txt
  - python3 setup.py install || python setup.py install

# commands to run tests
script:
  # open app from CLI
  - color-matcher -h
  # trigger unit tests
  - python3 -m test.unit_test || python -m test.unit_test

before_deploy:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      pip3 install --upgrade twine;
      python3 setup.py sdist bdist_wheel;
      python3 -m twine upload --repository https://test.pypi.org/legacy/ dist/* -u __token__ -p $TEST_PYPI;
      python3 -m pip install --index-url https://test.pypi.org/simple/ color-matcher;
    fi

deploy:
  - provider: pypi
    user: __token__
    skip_cleanup: true
    skip_existing: true
    distributions: sdist bdist_wheel
    password:
      secure: XnQzT512uc7dPCSyXSAwpfb8X6AsP//VITfoe9fITcsUpqa3oH0FQYTbJClp7/nwfZ/VGM/dP9i0lWoQYoxbxulsd+Oqk2ub4QY7Joue2eaERxX0hcUyzFQQWfATz/FphkYt0I2uOCKvduy2fFpOW84mmxZx5l2C2bjsL9h6GLIbgZS9so7Xz4mxL/f3md6yY6vJ/Nirh9KCTq250Dv6BJMYFxVpTazfCb3CgTDcyXGO68xbYFqPWu7URYrQo7LcS89M3P4lTZegQOgI3lxkXlDUw7Ctu719UKXBvdOThvJeaAjeAQ14b7yAyzwo7pUEyOSdutIFq3Fcshl/AxfePVl9x/wFPPdokPMnp1JJfsRZleokGUveX7QQDLUVPrNFqWnxuJMTaE83+nrQ85Wv/J4dz1BYZHl+aIFzxVL9xlglmbI2OhUMomOZyo5SXZ/Z7CQ5yrRvaNuw3mjnIAkesOR44hzxyrM4vANCqvnXZFulXvq39+VnUEs1jU/hACHtjpqdpwzlSJ2rs1i48BqyjJwdka2PeKOEcaU5oFBB8VCMFiVHqS2OEYrwRuMd3RX7ErWyH5chsmN9TDOsI5JHiKWmhmwNj4f3hTU03SCnxUtnTB5aOgO2wTs5GpDt4Th1YaLXNlZhvbxNIQPMNp919hwh2T4o0mCxLE0a17Qrbpk=
    on:
      condition: $TRAVIS_OS_NAME = linux
