notifications:
  email: false

language: python            # this works for Linux but is an error on macOS or Windows
jobs:
  include:
    - name: "Python 3.8.0 on Xenial Linux"
      python: 3.8           # this works for Linux but is ignored on macOS or Windows
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
      before_install:
        - python3 --version
    - name: "Python 3.8.0 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH

# install dependencies
install:
  - pip3 install --upgrade pip  # all three OSes agree about 'pip3'
  - sudo pip3 install -r requirements.txt || pip3 install -r requirements.txt
  - python3 setup.py install || python setup.py install

# commands to run tests
script:
  # open app from CLI
  - color-matcher -h
  # trigger unit tests
  - python3 -m test.unit_test || python -m test.unit_test

before_deploy:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      pip3 install --upgrade twine;
      python3 setup.py sdist bdist_wheel;
      python3 -m twine upload --repository https://test.pypi.org/legacy/ dist/* -u __token__ -p $TEST_PYPI;
      python3 -m pip install --index-url https://test.pypi.org/simple/ color-matcher;
    fi

deploy:
  - provider: pypi
    user: __token__
    skip_cleanup: true
    skip_existing: true
    distributions: sdist bdist_wheel
    server: https://upload.pypi.org/legacy/
    password:
      secure: qDQL2/aCZWEfrrMxJFrSj36Qwr5IUOyrbNpknguo3GUe2N9w68cMXo8pOTFEf/59tkBlG8B3ZiBz05tr/LpuHaEq6mCICQ/9gsbBpllCHaZWM201n46oE/PZrNvBw4X+MDdMUCgfDcoJoQXTaQo97128Qihli4tYbjkrLvlTD21FgqGyFfVLQsdelXPpJd+mX8tTA6nMeqYMLjiPv8vdgcA5GLp35rsoWTJwKKrGeHcwFnrCfUQHXvBg2hrfTB9kXoLlBd9NGbjQaVFo5L8OXrp5lw91qo1HBnSht7gAaAMr3MSOimWjJMH8ItcY3C+Zzpmv/uY7Y4clmKBaNcN2X3bnLdm8N9SVb5N4K29pWY/yTxZkGXclSJIeu1FrRQG6o9dKoc8MywG+NnuVl03GMkhSROeMzw5nPgYkZwbDUQI7Cw4xXNCOLQML7a0QE1VcwCtO+xNiMmM2q7nwoZeYUcQvcyY4TMKrh/ZROfTnyAeKmvmq6TF4T1sWJFGPxtehm1XZ+Wosb8rP61ijPw+iRE7uWQaVjP+9eBwuzeNEGCA/nOP/F+945vnQKHC2W1Vj/YPdHyb+/2kf/kLV3PjcowyMO0Bm9H8eys/bhICRs/aWMl8XXJyv1mx2Ei4otEE0z0AttmkwVkBc7u5D3Y732aLWGPa4IivWG0p2DFNBhkk=
    on:
      condition: $TRAVIS_OS_NAME = linux
      branches:
        only:
          - master

  - provider: releases
    name: Release $TRAVIS_TAG
    skip_cleanup: true
    api_key:
      secure: HpkQsqXHzAd62Hc1f/eMdcRzluQo4cS44q8WbMrUTxMFjGQ822JPsO/s7uTZAs5FZZzE/cPUTyYU2c8Rmn9tg547v3D5Dy16eG5jr8dJqGKkwN3vggv4x7U8PiajAIhbmWRqde7ywduqq98kcipTXaATrCtYvCIfRb7H08qmozV5L30DYdICvTlgFVXu6wq/TzQsCqG2XzXiVyvlTq/JVnC+Tl2Kl/33sDa9kJoaQbib4yNZlx5zWTOydkQQvTvK3O9HvHF5ZpWiSxbrg70C6zFQKscpmcpGth/FJEWoQxZvO91jUWBU1Thl5RgrQIZlSQFGfoVioTamCKy219ytlbgpmxvyZzeO4FirNoJ5xDKWy2HfY9JQJVt2cMi1kbniRfw3nSZRig7pGjg07eamvb38a5FWWyQe7gt/Obcbf0lyAQQVeo9HiktETRX8tAnfJjxv2qrLoYUuH0n27XZP+CJfLK35j6ptoYeesmyiZgYSYt2M7exhMP1UX+ts977nnmf7/JZIOg/Ytm4+Ba4FzIyvGPizKTSYyGmcLYYoW0LIdYkAO/mr/PSvrjdt6p9dZcNAKBMufrgwAuH3tyQgS+pAO8h4GFwfG8OrBR/eoBBJf5QaZj/YvZwWLj55bGr6+g4KSS3JVeFvx2xCLKs640gVtoQQF/682IYuGGU3J2g=
    file_glob: true
    file:
      - /dist/*.whl
      - /dist/*.tar.gz
    draft: true
    on:
      repo: hahnec/color-matcher
      condition: $TRAVIS_OS_NAME = linux
      branches:
        only:
          - master