notifications:
  email: false

language: python            # this works for Linux but is an error on macOS or Windows
jobs:
  include:
    - name: "Python 3.8.0 on Xenial Linux"
      python: 3.8           # this works for Linux but is ignored on macOS or Windows
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
      before_install:
        - python3 --version
    - name: "Python 3.8.0 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH

# install dependencies
install:
  - pip3 install --upgrade pip  # all three OSes agree about 'pip3'
  - sudo pip3 install -r requirements.txt || pip3 install -r requirements.txt
  - python3 setup.py install || python setup.py install

# commands to run tests
script:
  # open app from CLI
  - color-matcher -h
  # trigger unit tests
  - python3 test/unit_test.py || python test/unit_test.py

after_deploy:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      pip3 install --upgrade twine;
      python3 setup.py sdist bdist_wheel;
      python3 -m twine upload --repository testpypi dist/* -u hahnec -p $TEST_PYPI;
      python3 -m pip install --index-url https://test.pypi.org/simple/ color-matcher;
    fi