notifications:
  email: false

language: python            # this works for Linux but is an error on macOS or Windows
jobs:
  include:
    - name: "Python 3.8.0 on Xenial Linux"
      python: 3.8           # this works for Linux but is ignored on macOS or Windows
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
      before_install:
        - python3 --version
    - name: "Python 3.8.0 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH

# install dependencies
install:
  - pip3 install --upgrade pip  # all three OSes agree about 'pip3'
  - sudo pip3 install -r requirements.txt || pip3 install -r requirements.txt
  - python3 setup.py install || python setup.py install

# commands to run tests
script:
  # open app from CLI
  - color-matcher -h
  # trigger unit tests
  - python3 -m test.unit_test || python -m test.unit_test

#after_deploy:
#  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
#      pip3 install --upgrade twine;
#      python3 setup.py sdist bdist_wheel;
#      python3 -m twine upload --repository testpypi dist/* -u hahnec -p $TEST_PYPI --verbose;
#      python3 -m pip install --index-url https://test.pypi.org/simple/ color-matcher;
#    fi

deploy:
  - provider: pypi
    user: hahnec
    skip_cleanup: true
    skip_existing: true
    distributions: sdist bdist_wheel
    server: https://test.pypi.org/legacy/
    password:
      secure: FMqsSA6Pauzq2AJnWAdWfyYMENKFe/socNVwgdx9df7XNl27ykvzDMH2DoRJp2Jw3SDwriS0l0wig/MXmQvTh8PZ7tfwl4obqjEGZq/P3vDoSPvU4RQhlghHN2NrJijJxmp2x5p3k0E7Md57kqepkLOZi9Tx9tVYF5OIQ/vfvOaEXpguxf1jnPMVY3VhzYKbGvx31d2yKoGWm/wtzxAqjORUfs5iFObU/EumlPVCBxJynpRFDKozvHcIahwo/8RtdPap/whDZVYr8RcNC//Lub35yXObuPabbg8+T2ofd/4I3c4TpHuwcURMvGMS7W2y9Tcre/dcz+XP2WlOothGQZk3gQMLPI5RRL2UXYDi/GiwCYZi5iXl/ewgTh7CFSnvY+y0ojbU+dpDTjCJJda+W9uzzlb+BrgTSFi4WU0vjjACYTTxgSeM1Q7qhUdZqi0osoAz3yyKBVu4oVH6qG01jqGi9qwzitSsFD00J/LgATLEAqVlm7K6mkn9Zl09b0bDM4WlZ+Ova1c8wg8Al9r+VjM/x5XtlEUTymObDXVaxySqxkYPt5iUOLALz6AUPYJKIM+Na59vKAxQ0hyKzbIZHB1DPIN/yDNxaj/k53TWzlVwvLtiniSwRnyAsfMiGqaphs7F/UYL/fHysJjW8L9HNhDQZJe/gAXcctgnl9CpoHA=
