notifications:
  email: false

language: python            # this works for Linux but is an error on macOS or Windows
jobs:
  include:
    - name: "Python 3.8.0 on Xenial Linux"
      python: 3.8           # this works for Linux but is ignored on macOS or Windows
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
      before_install:
        - python3 --version
    - name: "Python 3.8.0 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH

# install dependencies
install:
  - pip3 install --upgrade pip  # all three OSes agree about 'pip3'
  - sudo pip3 install -r requirements.txt || pip3 install -r requirements.txt
  - python3 setup.py install || python setup.py install

# commands to run tests
script:
  # open app from CLI
  - color-matcher -h
  # trigger unit tests
  - python3 -m test.unit_test || python -m test.unit_test

#after_deploy:
#  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
#      pip3 install --upgrade twine;
#      python3 setup.py sdist bdist_wheel;
#      python3 -m twine upload --repository testpypi dist/* -u hahnec -p $TEST_PYPI --verbose;
#      python3 -m pip install --index-url https://test.pypi.org/simple/ color-matcher;
#    fi

deploy:
  provider: pypi
  user: hahnec
  skip_existing: true
  server: https://test.pypi.org/legacy/
  password:
    secure: vpZFMjF6aNLXipbKvCsY0wL7Cc6Cz3WvBT6U/UPhjhvPSVJylk4krPjYrWksPTeV5MRPGWrozYb1F0+aKufn8zKM6rfuiYEtZk+rjNt2QgQc2M3MVC7RzpUkEruVJQAegCGW+PYg5ONMzTLrBXpCJDe+ZigM4yPh/TjD9CGUeDhkw78x2lyPCFfqvlZmpuUtBtk8cNSZnQRRo59+6P7+XP1q4MnMghYi0idcs4yFmrIDOJfg3BBen8uM60vVFOq55hOvq6bgKAxd099LRVTtXmDuted/22IaKVBdg5epUjd1exXjAsAnVK6IAUtapDTJaZA7YZuKwHHafoDZixWiyuRXowe4W4QdNS863Ty5U8fxZj9HLMFnaBqgQhHzBM7ZuJ8GMJDx9KiMVJmiBP1R7DpC4zMgTIVYew6yGxdy5B6io9rVPvQtP7VAwNCpAsBz1WbVqzcLyewqjokGvNtAbpWtpU1H7OGqfRR8aJwLVQ3U5VN9rJMi8k7vHg7g5Z7/RiRFo6tjmZpWBt9MRdmAl5xgTDUh7OBVrRrRBg4AKOxRuKGU+ekylv2i0qJt06yCT6oEtbxIodliu5xgkHC3Z9mpTXydnV0dN3wLb/PdtMXek5jpaFAg6zSbH6nT70HYpn6L/Gc4WXcNH+lTDPpQpttW88HB46VMja8miinWdJA=