notifications:
  email: false

language: python            # this works for Linux but is an error on macOS or Windows
jobs:
  include:
    - name: "Python 3.8.0 on Xenial Linux"
      python: 3.8           # this works for Linux but is ignored on macOS or Windows
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
      before_install:
        - python3 --version
    - name: "Python 3.8.0 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH

# install dependencies
install:
  - pip3 install --upgrade pip  # all three OSes agree about 'pip3'
  - sudo pip3 install -r requirements.txt || pip3 install -r requirements.txt
  - python3 setup.py install || python setup.py install

# commands to run tests
script:
  # open app from CLI
  - color-matcher -h
  # trigger unit tests
  - python3 -m test.unit_test || python -m test.unit_test

#after_deploy:
#  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
#      pip3 install --upgrade twine;
#      python3 setup.py sdist bdist_wheel;
#      python3 -m twine upload --repository testpypi dist/* -u hahnec -p $TEST_PYPI --verbose;
#      python3 -m pip install --index-url https://test.pypi.org/simple/ color-matcher;
#    fi

deploy:
  - provider: pypi
    user: __token__
    skip_cleanup: true
    skip_existing: true
    distributions: sdist bdist_wheel
    server: https://test.pypi.org/legacy/
    password:
      secure: gwkrllXdA1pPPrg9ADhQusvyLkOuQ5AXAEDUpzHWI+VEn4TdAu/PZnsF1mEYdDvAGgqzo16O1hJDFt6EiqsvBHkFTaLSv2pmSqG/OfE88ENYx0usncJdqchxz++XWY1uEkjC276RsxIa3Mq4ocajtHlJ5c6ZzyH0Q5AtZqvdMYCWGRjemWrZC+iTFwN7V5JnDtRlRuRN3vq4f/TJkBpi+ZzEt5pVER/bL/Rh9H5XNMdXlyTz+AMRyiqXciCb28mmpJZax+vXwoIMVKyet6INrz9MFGjzye3+zbElaeZtaFoqyjNIjODLkeJXbMWfFJNGv2vyResqhbIH0zn5tobf52Kfw9lGG7SNAu65QXMCz6f0UNwlc0H9B9M795ugpdcEPAFqNz0vdhtk4s233Ptc+kHa3gfBpE1Kk8RtMqM5TIVwuNpRT0Bgl12vqBpsyK6pGbDmwhkFs5myXRnT/D/47jDKOzmJLGkC6iTdt3H6GVKFcF/O4bjfUy9Gw971jSC4FCygrLqqZOJH/mT6/IoknzbnzmPShEo6NFGBqAfSQXLnjlIyPAKKVUF40cJuPGgtXBgodDNakf/vefbv1eh0bLDcA7kdVi1XuaJsQBpqbpQhBAjZH4k64lIExBrOLWp1Ff9RpK9+TnjnZDPXvUT/kKM45O2/lSbCUFVCL0gKKNc=
